name: Daily Mail

on:
  workflow_dispatch:
  schedule:
    - cron: '48 13 * * *'

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run scheduler
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PWD: ${{ secrets.GMAIL_APP_PWD }}
        run: python scheduler.py
